/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author HP
 */
public class ViewProducto extends javax.swing.JFrame {

    /**
     * Creates new form ViewProveedores
     */
    public ViewProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jl_idproducto = new javax.swing.JLabel();
        jl_idsucursal = new javax.swing.JLabel();
        jl_nombre = new javax.swing.JLabel();
        jl_marca = new javax.swing.JLabel();
        jl_tipo_producto = new javax.swing.JLabel();
        jl_existencia = new javax.swing.JLabel();
        jl_preciomayoreo = new javax.swing.JLabel();
        jtf_idproducto = new javax.swing.JTextField();
        jtf_nombre = new javax.swing.JTextField();
        jtf_marca = new javax.swing.JTextField();
        jtf_tipo_producto = new javax.swing.JTextField();
        jtf_existencia = new javax.swing.JTextField();
        jtf_preciomayoreo = new javax.swing.JTextField();
        jtf_idsucursal = new javax.swing.JTextField();
        jl_preciounitario = new javax.swing.JLabel();
        jtf_preciounitario = new javax.swing.JTextField();
        jtf_descripcion = new javax.swing.JTextField();
        jl_descripcion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jp_navegacion = new javax.swing.JPanel();
        jbtn_primero = new javax.swing.JButton();
        jbtn_anterior = new javax.swing.JButton();
        jbtn_siguiente = new javax.swing.JButton();
        jbtn_ultimo = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jp_modificacionbd = new javax.swing.JPanel();
        jbtn_nuevo = new javax.swing.JButton();
        jbtn_guardar = new javax.swing.JButton();
        jbtn_borrar = new javax.swing.JButton();
        jbtn_modificar = new javax.swing.JButton();
        jbtn_cancelarnuevo = new javax.swing.JButton();
        jp_botonesalternativos = new javax.swing.JPanel();
        jbtn_guardar1 = new javax.swing.JButton();
        jbtn_cancelarmodificar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jl_titulo = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 40, 580, 10);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        jl_idproducto.setText("id_producto");

        jl_idsucursal.setText("Id sucursal");

        jl_nombre.setText("Nombre producto");

        jl_marca.setText("Marca");

        jl_tipo_producto.setText("Tipo producto");

        jl_existencia.setText("Existencia");

        jl_preciomayoreo.setText("Precio mayoreo");

        jtf_idproducto.setBackground(new java.awt.Color(204, 204, 204));
        jtf_idproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_idproductoActionPerformed(evt);
            }
        });

        jtf_nombre.setBackground(new java.awt.Color(204, 204, 204));

        jtf_marca.setBackground(new java.awt.Color(204, 204, 204));

        jtf_tipo_producto.setBackground(new java.awt.Color(204, 204, 204));

        jtf_existencia.setBackground(new java.awt.Color(204, 204, 204));

        jtf_preciomayoreo.setBackground(new java.awt.Color(204, 204, 204));

        jtf_idsucursal.setBackground(new java.awt.Color(204, 204, 204));

        jl_preciounitario.setText("Precio unitario");

        jtf_preciounitario.setBackground(new java.awt.Color(204, 204, 204));

        jtf_descripcion.setBackground(new java.awt.Color(204, 204, 204));

        jl_descripcion.setText("Descripcion");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jl_preciounitario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jl_tipo_producto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jl_existencia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jl_marca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jl_nombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jl_idproducto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jl_preciomayoreo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jl_idsucursal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jl_descripcion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtf_idsucursal)
                    .addComponent(jtf_idproducto)
                    .addComponent(jtf_nombre)
                    .addComponent(jtf_marca)
                    .addComponent(jtf_tipo_producto)
                    .addComponent(jtf_preciomayoreo)
                    .addComponent(jtf_existencia, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtf_preciounitario, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                    .addComponent(jtf_descripcion))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_idproducto)
                    .addComponent(jtf_idproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_nombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_marca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_tipo_producto)
                    .addComponent(jtf_tipo_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_existencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_existencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_preciounitario)
                    .addComponent(jtf_preciounitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_preciomayoreo)
                    .addComponent(jtf_preciomayoreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_descripcion)
                    .addComponent(jtf_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_idsucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_idsucursal))
                .addGap(47, 47, 47))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 80, 420, 280);

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Producto ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 50, 600, 15);

        jp_navegacion.setBackground(new java.awt.Color(0, 102, 102));

        jbtn_primero.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        jbtn_primero.setText("|<");

        jbtn_anterior.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        jbtn_anterior.setText("<<");

        jbtn_siguiente.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        jbtn_siguiente.setText(">>");

        jbtn_ultimo.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        jbtn_ultimo.setText(">|");

        jButton9.setText("jButton5");

        javax.swing.GroupLayout jp_navegacionLayout = new javax.swing.GroupLayout(jp_navegacion);
        jp_navegacion.setLayout(jp_navegacionLayout);
        jp_navegacionLayout.setHorizontalGroup(
            jp_navegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_navegacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtn_primero, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_anterior, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_ultimo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(jp_navegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jp_navegacionLayout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addComponent(jButton9)
                    .addContainerGap(307, Short.MAX_VALUE)))
        );
        jp_navegacionLayout.setVerticalGroup(
            jp_navegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_navegacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_navegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_primero)
                    .addComponent(jbtn_ultimo)
                    .addComponent(jbtn_siguiente)
                    .addComponent(jbtn_anterior))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jp_navegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_navegacionLayout.createSequentialGroup()
                    .addContainerGap(14, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(33, 33, 33)))
        );

        getContentPane().add(jp_navegacion);
        jp_navegacion.setBounds(0, 380, 420, 40);

        jp_modificacionbd.setBackground(new java.awt.Color(0, 102, 102));

        jbtn_nuevo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbtn_nuevo.setText("Nuevo ");

        jbtn_guardar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbtn_guardar.setText("Guardar");

        jbtn_borrar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbtn_borrar.setText("Borrar Registro");
        jbtn_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_borrarActionPerformed(evt);
            }
        });

        jbtn_modificar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbtn_modificar.setText("Modificar");

        jbtn_cancelarnuevo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbtn_cancelarnuevo.setText("Cancelar");

        javax.swing.GroupLayout jp_modificacionbdLayout = new javax.swing.GroupLayout(jp_modificacionbd);
        jp_modificacionbd.setLayout(jp_modificacionbdLayout);
        jp_modificacionbdLayout.setHorizontalGroup(
            jp_modificacionbdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_modificacionbdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_modificacionbdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtn_borrar, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(jbtn_nuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn_guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn_modificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn_cancelarnuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_modificacionbdLayout.setVerticalGroup(
            jp_modificacionbdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_modificacionbdLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtn_nuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_cancelarnuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_modificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_guardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_borrar)
                .addGap(16, 16, 16))
        );

        getContentPane().add(jp_modificacionbd);
        jp_modificacionbd.setBounds(440, 80, 138, 166);

        jp_botonesalternativos.setBackground(new java.awt.Color(0, 102, 102));

        jbtn_guardar1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbtn_guardar1.setText("Guardar ");

        jbtn_cancelarmodificar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbtn_cancelarmodificar.setText("Cancelar");

        javax.swing.GroupLayout jp_botonesalternativosLayout = new javax.swing.GroupLayout(jp_botonesalternativos);
        jp_botonesalternativos.setLayout(jp_botonesalternativosLayout);
        jp_botonesalternativosLayout.setHorizontalGroup(
            jp_botonesalternativosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_botonesalternativosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_botonesalternativosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtn_cancelarmodificar, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(jbtn_guardar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jp_botonesalternativosLayout.setVerticalGroup(
            jp_botonesalternativosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_botonesalternativosLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jbtn_cancelarmodificar)
                .addGap(18, 18, 18)
                .addComponent(jbtn_guardar1)
                .addContainerGap())
        );

        getContentPane().add(jp_botonesalternativos);
        jp_botonesalternativos.setBounds(440, 260, 140, 90);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/391.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-1, 3, 600, 470);

        jl_titulo.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jl_titulo.setForeground(new java.awt.Color(255, 255, 255));
        jl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_titulo.setText("Ferreterias ACME");
        getContentPane().add(jl_titulo);
        jl_titulo.setBounds(0, 0, 600, 32);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(10, 40, 580, 10);

        jMenuBar1.setBackground(new java.awt.Color(255, 153, 51));
        setJMenuBar(jMenuBar1);

        setBounds(0, 0, 614, 514);
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_idproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_idproductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_idproductoActionPerformed

    private void jbtn_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_borrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_borrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton9;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JSeparator jSeparator1;
    public javax.swing.JSeparator jSeparator2;
    public javax.swing.JButton jbtn_anterior;
    public javax.swing.JButton jbtn_borrar;
    public javax.swing.JButton jbtn_cancelarmodificar;
    public javax.swing.JButton jbtn_cancelarnuevo;
    public javax.swing.JButton jbtn_guardar;
    public javax.swing.JButton jbtn_guardar1;
    public javax.swing.JButton jbtn_modificar;
    public javax.swing.JButton jbtn_nuevo;
    public javax.swing.JButton jbtn_primero;
    public javax.swing.JButton jbtn_siguiente;
    public javax.swing.JButton jbtn_ultimo;
    public javax.swing.JLabel jl_descripcion;
    public javax.swing.JLabel jl_existencia;
    public javax.swing.JLabel jl_idproducto;
    public javax.swing.JLabel jl_idsucursal;
    public javax.swing.JLabel jl_marca;
    public javax.swing.JLabel jl_nombre;
    public javax.swing.JLabel jl_preciomayoreo;
    public javax.swing.JLabel jl_preciounitario;
    public javax.swing.JLabel jl_tipo_producto;
    public javax.swing.JLabel jl_titulo;
    public javax.swing.JPanel jp_botonesalternativos;
    public javax.swing.JPanel jp_modificacionbd;
    public javax.swing.JPanel jp_navegacion;
    public javax.swing.JTextField jtf_descripcion;
    public javax.swing.JTextField jtf_existencia;
    public javax.swing.JTextField jtf_idproducto;
    public javax.swing.JTextField jtf_idsucursal;
    public javax.swing.JTextField jtf_marca;
    public javax.swing.JTextField jtf_nombre;
    public javax.swing.JTextField jtf_preciomayoreo;
    public javax.swing.JTextField jtf_preciounitario;
    public javax.swing.JTextField jtf_tipo_producto;
    // End of variables declaration//GEN-END:variables
}
