/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Edgar
 */
public class ViewReportes extends javax.swing.JFrame {

    /**
     * Creates new form ViewReportes
     */
    public ViewReportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_titulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jm_archivo = new javax.swing.JMenu();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jmi_cerrar_sesion = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jmi_menu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jl_titulo.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jl_titulo.setForeground(new java.awt.Color(255, 255, 255));
        jl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_titulo.setText("Ferreterias ACME");
        getContentPane().add(jl_titulo);
        jl_titulo.setBounds(0, 0, 555, 32);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 38, 533, 11);

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Reportes del dia");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 50, 555, 15);

        jTextArea1.setBackground(new java.awt.Color(255, 171, 45));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 70, 530, 170);

        jLabel2.setText("Fecha:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 83, 48, 14);

        jLabel3.setText("23542525");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(76, 83, 68, 14);

        jButton1.setBackground(new java.awt.Color(204, 102, 0));
        jButton1.setText("Guardar");
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 250, 124, 23);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/391.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 560, 290);

        jMenuBar1.setBackground(new java.awt.Color(255, 153, 51));

        jm_archivo.setBackground(new java.awt.Color(255, 51, 0));
        jm_archivo.setText("Archivo");
        jm_archivo.add(jSeparator2);

        jmi_cerrar_sesion.setBackground(new java.awt.Color(255, 204, 51));
        jmi_cerrar_sesion.setText("Cerrar Sesión");
        jm_archivo.add(jmi_cerrar_sesion);
        jm_archivo.add(jSeparator3);

        jmi_menu.setBackground(new java.awt.Color(255, 204, 51));
        jmi_menu.setText("Menu");
        jm_archivo.add(jmi_menu);

        jMenuBar1.add(jm_archivo);

        setJMenuBar(jMenuBar1);

        setBounds(0, 0, 571, 351);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewReportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JTextArea jTextArea1;
    public javax.swing.JLabel jl_titulo;
    private javax.swing.JMenu jm_archivo;
    private javax.swing.JMenuItem jmi_cerrar_sesion;
    private javax.swing.JMenuItem jmi_menu;
    // End of variables declaration//GEN-END:variables
}
