/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author LAB 4
 */
public class ViewCrearCuenta extends javax.swing.JFrame {

    /**
     * Creates new form ViewCrearCuenta
     */
    public ViewCrearCuenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jl_titulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jl_nombre = new javax.swing.JLabel();
        jtf_nombre = new javax.swing.JTextField();
        jl_apaterno = new javax.swing.JLabel();
        jtf_apaterno = new javax.swing.JTextField();
        jl_amaterno = new javax.swing.JLabel();
        jtf_amaterno = new javax.swing.JTextField();
        jl_telefono = new javax.swing.JLabel();
        jtf_telefono = new javax.swing.JTextField();
        jl_calle = new javax.swing.JLabel();
        jtf_calle = new javax.swing.JTextField();
        jl_numero = new javax.swing.JLabel();
        jtf_numero = new javax.swing.JTextField();
        jl_colonia = new javax.swing.JLabel();
        jtf_colonia = new javax.swing.JTextField();
        jl_ciudad = new javax.swing.JLabel();
        jtf_ciudad = new javax.swing.JTextField();
        jl_cp = new javax.swing.JLabel();
        jtf_cp = new javax.swing.JTextField();
        jl_estado = new javax.swing.JLabel();
        jtf_estado = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jl_nombre_usuario = new javax.swing.JLabel();
        jl_tipo_usuario = new javax.swing.JLabel();
        jl_sucursal = new javax.swing.JLabel();
        jl_contrasenia = new javax.swing.JLabel();
        jl_rep_contrasenia = new javax.swing.JLabel();
        jtf_nombre_usuario = new javax.swing.JTextField();
        jtf_sucursal = new javax.swing.JTextField();
        jcb_tipo_usuario = new javax.swing.JComboBox<>();
        jpf_contrasenia = new javax.swing.JPasswordField();
        jpf_rep_contrasenia = new javax.swing.JPasswordField();
        jl_id = new javax.swing.JLabel();
        jtf_id = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jp_navegacion = new javax.swing.JPanel();
        jbtn_primero = new javax.swing.JButton();
        jbtn_anterior = new javax.swing.JButton();
        jbtn_siguiente = new javax.swing.JButton();
        jbtn_ultimo = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jp_modificacionbd = new javax.swing.JPanel();
        jbtn_nuevo = new javax.swing.JButton();
        jbtn_guardar = new javax.swing.JButton();
        jbtn_borrar = new javax.swing.JButton();
        jbtn_modificar = new javax.swing.JButton();
        jbtn_cancelarnuevo = new javax.swing.JButton();
        jp_botonesalternativos = new javax.swing.JPanel();
        jbtn_guardarm = new javax.swing.JButton();
        jbtn_cancelarmodificar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jm_archivo = new javax.swing.JMenu();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jmi_cerrar_sesion = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jmi_menu = new javax.swing.JMenuItem();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jl_titulo.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jl_titulo.setForeground(new java.awt.Color(255, 255, 255));
        jl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_titulo.setText("Ferreterias ACME");
        getContentPane().add(jl_titulo);
        jl_titulo.setBounds(20, 10, 570, 32);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 40, 560, 10);

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));

        jl_nombre.setText("Nombre:");

        jtf_nombre.setBackground(new java.awt.Color(204, 204, 204));
        jtf_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_nombreActionPerformed(evt);
            }
        });

        jl_apaterno.setText("Apellido Paterno:");

        jtf_apaterno.setBackground(new java.awt.Color(204, 204, 204));
        jtf_apaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_apaternoActionPerformed(evt);
            }
        });

        jl_amaterno.setText("Apellido Materno:");

        jtf_amaterno.setBackground(new java.awt.Color(204, 204, 204));
        jtf_amaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_amaternoActionPerformed(evt);
            }
        });

        jl_telefono.setText("Telefono:");

        jtf_telefono.setBackground(new java.awt.Color(204, 204, 204));
        jtf_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_telefonoActionPerformed(evt);
            }
        });

        jl_calle.setText("Calle:");

        jtf_calle.setBackground(new java.awt.Color(204, 204, 204));
        jtf_calle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_calleActionPerformed(evt);
            }
        });

        jl_numero.setText("Numero Exterior:");

        jtf_numero.setBackground(new java.awt.Color(204, 204, 204));
        jtf_numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_numeroActionPerformed(evt);
            }
        });

        jl_colonia.setText("Colonia");

        jtf_colonia.setBackground(new java.awt.Color(204, 204, 204));
        jtf_colonia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_coloniaActionPerformed(evt);
            }
        });

        jl_ciudad.setText("Ciudad");

        jtf_ciudad.setBackground(new java.awt.Color(204, 204, 204));
        jtf_ciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_ciudadActionPerformed(evt);
            }
        });

        jl_cp.setText("Codigo Postal");

        jtf_cp.setBackground(new java.awt.Color(204, 204, 204));
        jtf_cp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_cpActionPerformed(evt);
            }
        });

        jl_estado.setText("Estado:");

        jtf_estado.setBackground(new java.awt.Color(204, 204, 204));
        jtf_estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_estadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jl_cp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jl_ciudad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jl_colonia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jl_numero, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(jl_estado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_cp, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtf_ciudad, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtf_colonia, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtf_numero)
                            .addComponent(jtf_estado)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jl_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jl_calle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jl_telefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jl_amaterno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jl_apaterno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_telefono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                            .addComponent(jtf_amaterno, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtf_nombre, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtf_apaterno)
                            .addComponent(jtf_calle))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_nombre)
                    .addComponent(jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_apaterno)
                    .addComponent(jtf_apaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_amaterno)
                    .addComponent(jtf_amaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_telefono)
                    .addComponent(jtf_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_calle)
                    .addComponent(jtf_calle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_numero)
                    .addComponent(jtf_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_colonia)
                    .addComponent(jtf_colonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_ciudad)
                    .addComponent(jtf_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_cp)
                    .addComponent(jtf_cp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_estado)
                    .addComponent(jtf_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 56, 295, 321);

        jPanel2.setBackground(new java.awt.Color(255, 153, 51));

        jl_nombre_usuario.setText("Nombre de Usuario:");

        jl_tipo_usuario.setText("Tipo de Usuario:");

        jl_sucursal.setText("Sucursal(ID):");

        jl_contrasenia.setText("Contraseña:");

        jl_rep_contrasenia.setText("Repetir Contraseña:");

        jtf_nombre_usuario.setBackground(new java.awt.Color(204, 204, 204));
        jtf_nombre_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_nombre_usuarioActionPerformed(evt);
            }
        });

        jtf_sucursal.setBackground(new java.awt.Color(204, 204, 204));
        jtf_sucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_sucursalActionPerformed(evt);
            }
        });

        jcb_tipo_usuario.setBackground(new java.awt.Color(204, 204, 204));
        jcb_tipo_usuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Empleado" }));

        jpf_contrasenia.setBackground(new java.awt.Color(204, 204, 204));

        jpf_rep_contrasenia.setBackground(new java.awt.Color(204, 204, 204));

        jl_id.setText("ID:");

        jtf_id.setBackground(new java.awt.Color(204, 204, 204));
        jtf_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_idActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_rep_contrasenia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jl_tipo_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jl_sucursal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jl_contrasenia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jl_nombre_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jl_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtf_nombre_usuario)
                    .addComponent(jpf_rep_contrasenia)
                    .addComponent(jpf_contrasenia)
                    .addComponent(jcb_tipo_usuario, 0, 114, Short.MAX_VALUE)
                    .addComponent(jtf_sucursal)
                    .addComponent(jtf_id))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_nombre_usuario)
                    .addComponent(jtf_nombre_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_tipo_usuario)
                    .addComponent(jcb_tipo_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_sucursal)
                    .addComponent(jtf_sucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_contrasenia)
                    .addComponent(jpf_contrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_rep_contrasenia)
                    .addComponent(jpf_rep_contrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_id)
                    .addComponent(jtf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(323, 56, 252, 200);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/391.jpg"))); // NOI18N
        jLabel17.setText("jLabel17");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(0, 0, 600, 60);

        jp_navegacion.setBackground(new java.awt.Color(0, 102, 102));

        jbtn_primero.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        jbtn_primero.setText("|<");

        jbtn_anterior.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        jbtn_anterior.setText("<<");

        jbtn_siguiente.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        jbtn_siguiente.setText(">>");

        jbtn_ultimo.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        jbtn_ultimo.setText(">|");

        jButton9.setText("jButton5");

        javax.swing.GroupLayout jp_navegacionLayout = new javax.swing.GroupLayout(jp_navegacion);
        jp_navegacion.setLayout(jp_navegacionLayout);
        jp_navegacionLayout.setHorizontalGroup(
            jp_navegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_navegacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtn_primero)
                .addGap(26, 26, 26)
                .addComponent(jbtn_anterior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jbtn_siguiente)
                .addGap(18, 18, 18)
                .addComponent(jbtn_ultimo)
                .addContainerGap())
            .addGroup(jp_navegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jp_navegacionLayout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addComponent(jButton9)
                    .addContainerGap(177, Short.MAX_VALUE)))
        );
        jp_navegacionLayout.setVerticalGroup(
            jp_navegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_navegacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_navegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_primero)
                    .addComponent(jbtn_ultimo)
                    .addComponent(jbtn_siguiente)
                    .addComponent(jbtn_anterior))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(jp_navegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_navegacionLayout.createSequentialGroup()
                    .addContainerGap(17, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(33, 33, 33)))
        );

        getContentPane().add(jp_navegacion);
        jp_navegacion.setBounds(10, 390, 290, 50);

        jp_modificacionbd.setBackground(new java.awt.Color(0, 102, 102));

        jbtn_nuevo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbtn_nuevo.setText("Nuevo ");

        jbtn_guardar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbtn_guardar.setText("Guardar");

        jbtn_borrar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbtn_borrar.setText("Borrar Registro");
        jbtn_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_borrarActionPerformed(evt);
            }
        });

        jbtn_modificar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbtn_modificar.setText("Modificar");

        jbtn_cancelarnuevo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbtn_cancelarnuevo.setText("Cancelar");

        javax.swing.GroupLayout jp_modificacionbdLayout = new javax.swing.GroupLayout(jp_modificacionbd);
        jp_modificacionbd.setLayout(jp_modificacionbdLayout);
        jp_modificacionbdLayout.setHorizontalGroup(
            jp_modificacionbdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_modificacionbdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_modificacionbdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtn_borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jp_modificacionbdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jbtn_guardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtn_modificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtn_cancelarnuevo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                        .addComponent(jbtn_nuevo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_modificacionbdLayout.setVerticalGroup(
            jp_modificacionbdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_modificacionbdLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtn_nuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_cancelarnuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_modificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_guardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_borrar)
                .addGap(16, 16, 16))
        );

        getContentPane().add(jp_modificacionbd);
        jp_modificacionbd.setBounds(460, 270, 110, 166);

        jp_botonesalternativos.setBackground(new java.awt.Color(0, 102, 102));

        jbtn_guardarm.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbtn_guardarm.setText("Guardar ");

        jbtn_cancelarmodificar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbtn_cancelarmodificar.setText("Cancelar");

        javax.swing.GroupLayout jp_botonesalternativosLayout = new javax.swing.GroupLayout(jp_botonesalternativos);
        jp_botonesalternativos.setLayout(jp_botonesalternativosLayout);
        jp_botonesalternativosLayout.setHorizontalGroup(
            jp_botonesalternativosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_botonesalternativosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_botonesalternativosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtn_guardarm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn_cancelarmodificar, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jp_botonesalternativosLayout.setVerticalGroup(
            jp_botonesalternativosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_botonesalternativosLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jbtn_cancelarmodificar)
                .addGap(18, 18, 18)
                .addComponent(jbtn_guardarm)
                .addContainerGap())
        );

        getContentPane().add(jp_botonesalternativos);
        jp_botonesalternativos.setBounds(320, 270, 130, 90);

        jMenuBar1.setBackground(new java.awt.Color(255, 153, 51));

        jm_archivo.setBackground(new java.awt.Color(255, 51, 0));
        jm_archivo.setText("Archivo");
        jm_archivo.add(jSeparator2);

        jmi_cerrar_sesion.setBackground(new java.awt.Color(255, 204, 51));
        jmi_cerrar_sesion.setText("Cerrar Sesión");
        jm_archivo.add(jmi_cerrar_sesion);
        jm_archivo.add(jSeparator3);

        jmi_menu.setBackground(new java.awt.Color(255, 204, 51));
        jmi_menu.setText("Menu");
        jm_archivo.add(jmi_menu);

        jMenuBar1.add(jm_archivo);

        setJMenuBar(jMenuBar1);

        setBounds(0, 0, 618, 518);
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_calleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_calleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_calleActionPerformed

    private void jtf_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_nombreActionPerformed

    private void jtf_apaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_apaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_apaternoActionPerformed

    private void jtf_amaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_amaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_amaternoActionPerformed

    private void jtf_telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_telefonoActionPerformed

    private void jtf_numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_numeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_numeroActionPerformed

    private void jtf_coloniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_coloniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_coloniaActionPerformed

    private void jtf_ciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_ciudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_ciudadActionPerformed

    private void jtf_cpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_cpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_cpActionPerformed

    private void jtf_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_estadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_estadoActionPerformed

    private void jtf_nombre_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_nombre_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_nombre_usuarioActionPerformed

    private void jtf_sucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_sucursalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_sucursalActionPerformed

    private void jbtn_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_borrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_borrarActionPerformed

    private void jpf_rep_contrasenia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpf_rep_contrasenia1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpf_rep_contrasenia1ActionPerformed

    private void jtf_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCrearCuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton9;
    public javax.swing.JLabel jLabel17;
    public javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JSeparator jSeparator1;
    public javax.swing.JPopupMenu.Separator jSeparator2;
    public javax.swing.JPopupMenu.Separator jSeparator3;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JButton jbtn_anterior;
    public javax.swing.JButton jbtn_borrar;
    public javax.swing.JButton jbtn_cancelarmodificar;
    public javax.swing.JButton jbtn_cancelarnuevo;
    public javax.swing.JButton jbtn_guardar;
    public javax.swing.JButton jbtn_guardarm;
    public javax.swing.JButton jbtn_modificar;
    public javax.swing.JButton jbtn_nuevo;
    public javax.swing.JButton jbtn_primero;
    public javax.swing.JButton jbtn_siguiente;
    public javax.swing.JButton jbtn_ultimo;
    public javax.swing.JComboBox<String> jcb_tipo_usuario;
    public javax.swing.JLabel jl_amaterno;
    public javax.swing.JLabel jl_apaterno;
    public javax.swing.JLabel jl_calle;
    public javax.swing.JLabel jl_ciudad;
    public javax.swing.JLabel jl_colonia;
    public javax.swing.JLabel jl_contrasenia;
    public javax.swing.JLabel jl_cp;
    public javax.swing.JLabel jl_estado;
    public javax.swing.JLabel jl_id;
    public javax.swing.JLabel jl_nombre;
    public javax.swing.JLabel jl_nombre_usuario;
    public javax.swing.JLabel jl_numero;
    public javax.swing.JLabel jl_rep_contrasenia;
    public javax.swing.JLabel jl_sucursal;
    public javax.swing.JLabel jl_telefono;
    public javax.swing.JLabel jl_tipo_usuario;
    public javax.swing.JLabel jl_titulo;
    public javax.swing.JMenu jm_archivo;
    public javax.swing.JMenuItem jmi_cerrar_sesion;
    public javax.swing.JMenuItem jmi_menu;
    public javax.swing.JPanel jp_botonesalternativos;
    public javax.swing.JPanel jp_modificacionbd;
    public javax.swing.JPanel jp_navegacion;
    public javax.swing.JPasswordField jpf_contrasenia;
    public javax.swing.JPasswordField jpf_rep_contrasenia;
    public javax.swing.JTextField jtf_amaterno;
    public javax.swing.JTextField jtf_apaterno;
    public javax.swing.JTextField jtf_calle;
    public javax.swing.JTextField jtf_ciudad;
    public javax.swing.JTextField jtf_colonia;
    public javax.swing.JTextField jtf_cp;
    public javax.swing.JTextField jtf_estado;
    public javax.swing.JTextField jtf_id;
    public javax.swing.JTextField jtf_nombre;
    public javax.swing.JTextField jtf_nombre_usuario;
    public javax.swing.JTextField jtf_numero;
    public javax.swing.JTextField jtf_sucursal;
    public javax.swing.JTextField jtf_telefono;
    // End of variables declaration//GEN-END:variables
}
