/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Edgar
 */
public class ViewMenu extends javax.swing.JFrame {

    /**
     * Creates new form ViewMenu
     */
    public ViewMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_titulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jbtn_productos = new javax.swing.JButton();
        jbtn_proveedores = new javax.swing.JButton();
        jbtn_clientes = new javax.swing.JButton();
        jbtn_compras = new javax.swing.JButton();
        jbtn_ventas = new javax.swing.JButton();
        jbtn_reportes = new javax.swing.JButton();
        jbtn_sucursales = new javax.swing.JButton();
        jbtn_empleados = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jm_archivo = new javax.swing.JMenu();
        jmi_borrar_cuenta = new javax.swing.JMenuItem();
        jmi_crear_cuenta = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jmi_cerrar_sesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 102));
        getContentPane().setLayout(null);

        jl_titulo.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jl_titulo.setForeground(new java.awt.Color(255, 255, 255));
        jl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_titulo.setText("Ferreterias ACME");
        getContentPane().add(jl_titulo);
        jl_titulo.setBounds(20, 10, 500, 32);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 40, 530, 10);

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));

        jbtn_productos.setBackground(new java.awt.Color(204, 204, 204));
        jbtn_productos.setText("Productos");
        jbtn_productos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtn_productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_productosActionPerformed(evt);
            }
        });

        jbtn_proveedores.setBackground(new java.awt.Color(204, 204, 204));
        jbtn_proveedores.setText("Proveedores");
        jbtn_proveedores.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtn_proveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_proveedoresActionPerformed(evt);
            }
        });

        jbtn_clientes.setBackground(new java.awt.Color(204, 204, 204));
        jbtn_clientes.setText("Clientes");
        jbtn_clientes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtn_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_clientesActionPerformed(evt);
            }
        });

        jbtn_compras.setBackground(new java.awt.Color(204, 204, 204));
        jbtn_compras.setText("Compras");
        jbtn_compras.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtn_compras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_comprasActionPerformed(evt);
            }
        });

        jbtn_ventas.setBackground(new java.awt.Color(204, 204, 204));
        jbtn_ventas.setText("Ventas");
        jbtn_ventas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtn_ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_ventasActionPerformed(evt);
            }
        });

        jbtn_reportes.setBackground(new java.awt.Color(204, 204, 204));
        jbtn_reportes.setText("Reportes");
        jbtn_reportes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtn_reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_reportesActionPerformed(evt);
            }
        });

        jbtn_sucursales.setBackground(new java.awt.Color(204, 204, 204));
        jbtn_sucursales.setText("Sucursales");
        jbtn_sucursales.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbtn_empleados.setBackground(new java.awt.Color(204, 204, 204));
        jbtn_empleados.setText("Empleados");
        jbtn_empleados.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtn_proveedores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                    .addComponent(jbtn_productos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn_clientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn_compras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn_ventas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn_reportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn_sucursales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn_empleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jbtn_productos)
                .addGap(8, 8, 8)
                .addComponent(jbtn_sucursales)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_proveedores)
                .addGap(4, 4, 4)
                .addComponent(jbtn_clientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_compras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_ventas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_reportes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_empleados)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 60, 530, 220);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/391.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 550, 300);

        jMenuBar1.setBackground(new java.awt.Color(255, 153, 51));

        jm_archivo.setBackground(new java.awt.Color(255, 51, 0));
        jm_archivo.setText("Archivo");

        jmi_borrar_cuenta.setBackground(new java.awt.Color(255, 204, 51));
        jmi_borrar_cuenta.setText("Borrar Cuenta Existente");
        jm_archivo.add(jmi_borrar_cuenta);

        jmi_crear_cuenta.setBackground(new java.awt.Color(255, 204, 51));
        jmi_crear_cuenta.setText("Crear Nueva Cuenta");
        jm_archivo.add(jmi_crear_cuenta);
        jm_archivo.add(jSeparator2);

        jmi_cerrar_sesion.setBackground(new java.awt.Color(255, 204, 51));
        jmi_cerrar_sesion.setText("Cerrar Sesión");
        jm_archivo.add(jmi_cerrar_sesion);

        jMenuBar1.add(jm_archivo);

        setJMenuBar(jMenuBar1);

        setBounds(0, 0, 567, 358);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_productosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_productosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_productosActionPerformed

    private void jbtn_comprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_comprasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_comprasActionPerformed

    private void jbtn_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_clientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_clientesActionPerformed

    private void jbtn_proveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_proveedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_proveedoresActionPerformed

    private void jbtn_reportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_reportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_reportesActionPerformed

    private void jbtn_ventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_ventasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_ventasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabel2;
    public javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JSeparator jSeparator1;
    public javax.swing.JPopupMenu.Separator jSeparator2;
    public javax.swing.JButton jbtn_clientes;
    public javax.swing.JButton jbtn_compras;
    public javax.swing.JButton jbtn_empleados;
    public javax.swing.JButton jbtn_productos;
    public javax.swing.JButton jbtn_proveedores;
    public javax.swing.JButton jbtn_reportes;
    public javax.swing.JButton jbtn_sucursales;
    public javax.swing.JButton jbtn_ventas;
    public javax.swing.JLabel jl_titulo;
    public javax.swing.JMenu jm_archivo;
    public javax.swing.JMenuItem jmi_borrar_cuenta;
    public javax.swing.JMenuItem jmi_cerrar_sesion;
    public javax.swing.JMenuItem jmi_crear_cuenta;
    // End of variables declaration//GEN-END:variables
}
